#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

chmod 755 make-javacfile.sh

source var.sh
# Compile java files
FILES=$(ls $SRC | sed 's/\.java'//g)
./make-javacfile.sh $FILES
